language: python
python:
- '3.6'
- '3.7'
- '3.8'
branches:
  except:
  - "/^(documentation).*$/i"
sudo: required
dist: xenial
services:
  - xvfb
addons:
  chrome: stable
cache: pip
install:
- pip install .
- pip install coveralls
- pip install pytest-cov
before_script:
- wget "http://chromedriver.storage.googleapis.com/78.0.3904.70/chromedriver_linux64.zip"
- unzip chromedriver_linux64.zip
- sudo mv chromedriver /usr/local/bin
- export DISPLAY=:99.0
- sleep 3
script:
- pytest --cov owasp_zap_historic -v
after_success:
- coveralls
deploy:
  provider: pypi
  user: __token__
  password:
    secure: pY3Gdmtyo2ARqU306qjp6B0XSif6kpeuvLKD+WBYupqbeus6uIXqBLbyxghlLXBAqfhLfy4zLpLcspZX5V/gcs/FTz6QEAEVNQZk7DePSLm787Z8ad817d8/B9rP7ivaGWpc5bBrU8T7/9LjEh+TIG8KspjQBlofweIzsaAjgRYesNFaYwKZru+WTsB3UYQlqwixIdopXYXthPazeg9+H3ieezEdsKXH44vF/vGsx0egTAzRJo9UPwGNVaDdcSNYasWaBSZ5SyUKfJ+K5mGiP/F8naeSi/ezLpnglEcjbWvxmQklBt3ugCtVMIh1G3gs1x0CTgDSuPlGlNHAK40y0pMZBN3psP++D1kk/ei7nVFWnU9YddEenyn/3Khku7Ql98KLCRpwACZPhIkwP4U801ZinNtipUeogThpCzylUssbhNiTGE7+fGtIbTpHgWRrzNXWOD9pGgx12kzGDu65plS9GAA96ANAyjDnMFTaB6S9iNbg32Ot6AZEhITArmmOEULtuJ+ITHl83ah4YsXEq3ftpFhdwwBpRSLFllV+Ib1CLEzNppNGhaSJEIhKb5w9XBaBbeQMiKw8bbA0/erwR2swnIpzvnk/sdpm8IsXnKP3tpvdJyO+zXxyaq6WIL0i2A0wjNHLkwrriOn4ggCkdhvMnf4rkwJZkt/ltIQyEMg=
  on:
    branch: master
    tags: true
  skip_existing: true
  distributions: "sdist bdist_wheel"
