language: python
python:
- '3.6'
- '3.7'
- '3.8'
branches:
  except:
  - "/^(documentation).*$/i"
sudo: required
dist: xenial
services:
  - xvfb
addons:
  chrome: stable
cache: pip
install:
- pip install .
- pip install coveralls
- pip install pytest-cov
before_script:
- wget "http://chromedriver.storage.googleapis.com/78.0.3904.70/chromedriver_linux64.zip"
- unzip chromedriver_linux64.zip
- sudo mv chromedriver /usr/local/bin
- export DISPLAY=:99.0
- sleep 3
script:
- pytest --cov owasp_zap_historic -v
after_success:
- coveralls
deploy:
  provider: pypi
  user: __token__
  password:
    secure: rK0Cn/igJ28n3RZLICnlKv6zed7QqL1NWpz3lY2yQGj3ZIDoxeEsjmST5IwpKuJkcEY5HyF3AW5F9fEkuWA8V7lgOVAft0BgvF23gBH5GiM1/YxDyfp4G7TXu/7RhQvfA8CZiZl+Jj1mkYbzVK9V5nwMOtYjEIxbj7xXvSXKazXNwixb2AsBJecVGPgOoYy9FGSZhwwcUxzvJ3ghzNmBk3JhJjwlLNeFz8u0Alwc5QCiITh4WDOYVGYjyrGqtgZcr7VOZ/USDfpRnnuWTlsf9EFz1dh2OjpcLTgjX4KEylEsIZmdmQ2Zcqr7K8C2q28S6BJhgXIa61ww31vDeloBNTz0KpYMIstuYWbZWO2HOcIUmZFta8Mx08Zj9rMUB6vkmhz70MqUICBRK8/7HQIwdNnO6+r0DubuWzAwbSVbfej5liG/R+VkLD5CI0h0M+bFxVf0Vs3w4280rA8WMX8vxqPlzZ621nxAq6M7AaZFcc4sS/evyJ+SAB2RmluDLgypxmz/YsbI75Dw+8YsAruSSx0pDSnpaIXQdcGgAeCYCtpVFIWL8Mvsx60niWwMfKab8Wq6uec1umEShbElWlv22xX83TMA9k64WbqSbvyMysslvm0m3GiLp1kTt8OgQXFJABcVIQ/1mqk0ctZjSbU2bAcKAnWLg0ze2OVJaOLXFtQ=
  on:
    branch: master
    tags: true
  skip_existing: true
  distributions: "sdist bdist_wheel"
