version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: robothistoric
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    networks:
      - rf
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - rf
  # rfhistoric
  # rfhistoric:
  #   depends_on:
  #     - db
  #   image: proget.accruentsystems.com/qe_docker/library/rfhistoric:latest
  #   restart: always
  #   ports:
  #     - '5000:5000'
  #   environment:
  #     SQLHOST: db
  #     PORT: 3306
  #     USERNAME: username
  #     PASSWORD: password
  #     FLASKHOST: 0.0.0.0
  #   links:
  #     - db
  #   networks:
  #     - rf
networks:
  rf:
volumes:
  db_data:
